### ISSUE TITLE
@types/graphql as devDependencies only

### ISSUE THREAD

**Issue by ribizli** [apollographql/graphql-subscriptions#100]
Don't publish this dependency with the module. It's just not needed at all.

**Comment by bradleyayers** [comment]
The `SubscriptionManager` export takes a `GraphQLSchema` parameter which comes from the `graphql` package. As far as I can tell it is needed…

What gave you the impression it was not needed?

**Comment by ribizli** [comment]
You are right, since `graphql` doesn't publish a `typing` it is needed. (see [link](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html))

My problem was the version what is installed by `graphql-subscriptions`. I needed the `subscribe` function for `SubscriptionServer`. I installed the newer version in my package, so it's working.

**Comment by ribizli** [comment]
Actually I have again the issue, after I updated to `@types/graphql@0.11.2`.

```
error TS2345: Argument of type '{ execute: (schema: GraphQLSchema, document: DocumentNode, rootValue?: any, contextValue?: any, v...' is not assignable to parameter of type 'ServerOptions'.
  Types of property 'schema' are incompatible.
    Type 'GraphQLSchema' is not assignable to type 'GraphQLSchema | undefined'.
      Type 'GraphQLSchema' is not assignable to type 'GraphQLSchema'. Two different types with this name exist, but they are unrelated.
        Types of property 'getType' are incompatible.
          Type '(name: string) => GraphQLType' is not assignable to type '(name: string) => GraphQLNamedType'.
            Type 'GraphQLType' is not assignable to type 'GraphQLNamedType'.
              Type 'GraphQLList<any>' is not assignable to type 'GraphQLNamedType'.
                Type 'GraphQLList<any>' is not assignable to type 'GraphQLInputObjectType'.
                  Property 'name' is missing in type 'GraphQLList<any>'.
```

**Comment by NeoPhi** [comment]
Can you see if https://github.com/apollographql/graphql-subscriptions/releases/tag/v0.5.0 addresses your issue?

**Comment by ribizli** [comment]
I guess it is hard to say, since `subscriptions-transport-ws` still requires the version `0.4.4`.

**Comment by dyst5422** [comment]
This issue is the bane of my existence.

**Comment by veeramarni** [comment]
I think it needs to move to `devDependencies`

**Comment by bradleyayers** [comment]
@veeramarni can you give an explanation for why you think it should be in `devDependencies` — ideally providing a counter argument to my earlier comment?

**Comment by ribizli** [comment]
An argument from me: if I'd like to use the newer graphql version (which might be backward compatible), but I get conflict of the typing as shown earlier.

**Comment by veeramarni** [comment]
`devDependencies` won't be pulled in target installation. If anyone wants to use the `types` they can include in their target `package.json`. 

Please see below for more details. 
https://github.com/Microsoft/types-publisher/issues/81
https://stackoverflow.com/questions/45176661/how-do-i-decide-whether-types-goes-into-dependencies-or-devdependencies

**Comment by bradleyayers** [comment]
@veeramarni I'm confused — the accepted answer on that stackoverflow question says it should be in `dependencies` rather than `devDependencies`.

**Comment by ribizli** [comment]
I've already accepted the fact it has to be published with the module (I temporary closed the issue; Typescript's official statement said the same).
I've reopened the issue because I need a statement, how can I use a different version of the types if it's needed (e.g. when I install a newer graphql vereion)? Maybe we have to stick to the same version, regardless a newer grqphql version is available? I'm still using the version 0.10.x in my project due to this. (And because the peer deps of apollo-express and grphql-tools don't allow the newest, but that's a different story).

**Comment by bradleyayers** [comment]
Are you able to try https://yarnpkg.com/en/docs/selective-version-resolutions#toc-how-to-use-it? I haven't heard of NPM having a similar facility unfortunately — in fact I'm not sure this would work in your case, but perhaps it's worth a shot.

**Comment by NeoPhi** [comment]
Release 0.5.2 moves this to devDependencies to support different versions of graphql.
