### ISSUE TITLE
Pass resolver arguments in asyncIteratorFactory

### ISSUE THREAD

**Issue by stalniy** [apollographql/graphql-subscriptions#102]
**Issue**:
I store my `PubSub` instance in Graphql `context` variable, so when using `withFilter` I can't access to it and return `asyncIterator` instance.

**Possible solution**:
I suggest to pass all resolvers arguments into `asyncIterator` factory function, so then I can read `PubSub` instance from `context`.

The fix is trivial, just to change [a line of code](https://github.com/apollographql/graphql-subscriptions/blob/master/src/with-filter.ts#L8). So, if you are ok with this I will make a PR

**Comment by srtucker22** [comment]
I was just running into the same thing and threw together #103 😃

**Comment by NeoPhi** [comment]
Closed via https://github.com/apollographql/graphql-subscriptions/releases/tag/v0.5.1
