### ISSUE TITLE
subscription completed

### ISSUE THREAD

**Issue by akatebi** [apollographql/graphql-subscriptions#131]
How do we publish the last value with the done field of false to complete a subscription?

**Comment by green-coder** [comment]
Please reformulate your question in a more comprehensible way.

**Comment by grantwwu** [comment]
Not sure what the question was asking, but when a subscription is terminated usually the transport is supposed to call return on the asyncIterator.

**Comment by sijad** [comment]
https://github.com/apollographql/apollo-client/issues/4163
