### ISSUE TITLE
Subscription "A" must select only one top level field

### ISSUE THREAD

**Issue by gauravmakkar** [apollographql/graphql-subscriptions#137]
Can't I subscribe to two or more data sets?

```
subscription A{
  userList{
    list {
      id
    }
  }
  ppsList{
    list {
      pps_id
      
    }
  }
  
}
```

```
const rootResolvers = {
    Subscription: {
        userList: {
            subscribe: pubsub.asyncIterator(USER_LIST_UPDATED)
        },

        ppsList:{
            subscribe:  pubsub.asyncIterator(PPS_LIST_UPDATED)
        }


    },
};
```

Response:
`{"type":"subscription_data","id":4,"payload":{"errors":[{"message":"Subscription \"A\" must select only one top level field.","locations":[{"line":7,"column":3}]}]}}`

**Comment by taybin** [comment]
That seems to be an undocumented requirement in graphql-js.

https://github.com/graphql/graphql-js/blob/261b99b0a643561ccfb217fe8ac0c2ac16b2c5d3/src/validation/rules/SingleFieldSubscriptions.js#L22-L26

**Comment by acao** [comment]
I'm getting this error with a single field?

```
subscription A{
  myMessages {
    id
  }
}
```

`Subscription A must select only one top level field.`

**Comment by acao** [comment]
Disregard - this is caused by not having the proper `MessageSubscriptionPayload` response in the `graphql-yoga` definition, in my case.

**Comment by grantwwu** [comment]
This is a documented requirement of the spec. http://facebook.github.io/graphql/draft/#sec-Single-root-field

**Comment by dandv** [comment]
@grantwwu: updated link: https://graphql.github.io/graphql-spec/draft/#sec-Single-root-field

What is the workaround for the common use case of subscribing to Create, Update, Delete operations?

**Comment by grantwwu** [comment]
I don't know.  I didn't write the spec.  Presumably changing your schema.
