### ISSUE TITLE
TypeScript type definition changed in `0.5.7`

### ISSUE THREAD

**Issue by akoenig** [apollographql/graphql-subscriptions#138]
I just figured that the TypeScript type definitions changed in `0.5.7` (which is not tagged btw). This breaks libraries that rely on the previous types, like [graphql-yoga](https://github.com/graphcool/graphql-yoga/issues/173). The version `0.5.6` which has been published to the npm registry ships with the `dist/subscriptions-manager.d.ts`; the release `0.5.7` does not ship with this file.

https://github.com/graphcool/graphql-yoga/issues/173

**Comment by tfiwm** [comment]
Any progress here?

**Comment by NeoPhi** [comment]
The inclusion of `subscriptions-manager` in any 0.5.x release was an error. That file was removed as part of the transition to support newer GraphQL versions.
