### ISSUE TITLE
resolve key in resolver doesn't resolve promise

### ISSUE THREAD

**Issue by daviestar** [apollographql/graphql-subscriptions#139]
Hello,

Just getting to grips with graphql subscriptions using this package.

I have a subscription like this:

```js
Subscription: {
  importQueueItemUpdate: {
    subscribe: () => {
      console.log('iq subscribe!')
      return subscription.asyncIterator('importQueueItemUpdate')
    },
    resolve: async (payload) => {
      // payload.newProperty = await do database query...
      console.log('iq resolve!', payload)
      return payload
    }
  }
}
```
It might be a poor design choice anyway, but I've found when `resolve` returns a promise the resulting data in the frontend (react-apollo subscribeToMore) is `null`.  This might be by design but it's not consistent with conventional resolvers and should maybe be noted.

**Comment by jamiter** [comment]
I wonder if this is a promise issue or a documentation issue that just got merged: https://github.com/apollographql/graphql-subscriptions/pull/134

**Comment by grantwwu** [comment]
@daviestar do you still need help with this?

**Comment by daviestar** [comment]
@grantwwu No thanks, I'm all round graphql subscriptions now.. apologies for not getting back to this issue before now 👍
