### ISSUE TITLE
Ack on message received by a client - feature

### ISSUE THREAD

**Issue by bginsburg** [apollographql/graphql-subscriptions#149]
I have this use case scenario which we implement graphql-subscriptions with RabbitMq.
I would like to have a way to ack a message I publish (make sure the client received it)
So I can ack back to RMQ and decide whether this message needs to go back to the queue or am I done processing it.

Do you currently support such a thing?

**Comment by grantwwu** [comment]
https://github.com/apollographql/graphql-subscriptions/issues/160 supports this use case, I think.

**Comment by grantwwu** [comment]
I think this is out of scope for this particular library, closing.  Let me know if you disagree.

In general these sorts of things are probably going to be done in a PubSubEngine implementation and not here.

**Comment by grantwwu** [comment]
http://facebook.github.io/graphql/draft/#sec-Subscription states that 
> There are intentionally no specifications for message acknowledgement, buffering, resend requests, or any other quality of service (QoS) details. Message serialization, transport mechanisms, and quality of service details should be chosen by the implementing service.

What about adding message IDs into the subscription payloads, and then ack'ing to the PubSub service out of band?

**Comment by bginsburg** [comment]
This is what we ended up doing but it would have been nice to just use RMQ with its out of box ack functionality.
So if the client fails to get the message it will automatically go back to the queue and will be picked up again.

**Comment by grantwwu** [comment]
I suppose it is possible to add this, but you'd probably want to take this up with https://github.com/apollographql/subscriptions-transport-ws instead.

**Comment by bginsburg** [comment]
Sure will! Thanks you!
