### ISSUE TITLE
Using subscriptions on microservice backend

### ISSUE THREAD

**Issue by f89688563** [apollographql/graphql-subscriptions#151]
I have setup a graphql gateway for several backends that have some subscriptions, those subscriptions works well on each backend but throw errors on the gateway.
Errors: Cannot return null for non-nullable field Subscription.newTeamMessage.

**Comment by NeoPhi** [comment]
That error is being generated by your GraphQL resolver attempting to `return null for non-nullable field` and is unrelated to subscription. Check that your two environments are generating payloads in the same way.
