### ISSUE TITLE
Mutualize graphql executions

### ISSUE THREAD

**Issue by Shahor** [apollographql/graphql-subscriptions#153]
Hello!

I'm building a real time application with graphql subscriptions and I am facing performance issues at the moment.

What I do is I use the `graphql subscriptions` more like a contract than for it's resolvers per say.

The data I want to pass through to the connected clients is precomputed and I know my audience from the start, therefore I don't need to run the graphql execution for as many sockets as I have connected. 

Once per payload is enough, and I could just use the result of that execution to all the users (the resolvers don't do anything related to the user so it doesn't matter really). 

I'm still producing some numbers about how this impacts our system and will update this issue once done, but I thought I would ask about this first here.

**Comment by NeoPhi** [comment]
If you don't define any custom resolvers then the default graphql object property lookup will be used which has minimal overhead. In this case the same payload can be sent to all clients listening on the same subscription.
