### ISSUE TITLE
Injecting the payload at the Subscription Level without Monkey Patching

### ISSUE THREAD

**Issue by MoonTahoe** [apollographql/graphql-subscriptions#165]
I was looking for a solution to inject payload data at the subscription level. I came up with something, but I was wondering if there is a more graceful of handling this requirement.

Consider a subscription called `instructions`. Let's say we always wanted to publish up to date info about the user who subscribed to instructions. You would have to do so at the subscription level:

```javascript
const resolvers = {
    ...
    Subscription = {

        instructions: {
            subscribe(_, args, { pubsub, currentUser }) {
                
                if (!currentUser) {
                    throw new Error('a user must be logged in to subscribe to instructions')
                }

                //
                //   Instead of returning the iterator I monkey patch the .next method 
                //   and force the payload value to be the currentUser who subscribed.
                //

                const iterator = pubsub.asyncIterator('new-instructions')
                const next = iterator.next
                iterator.next = () => next()
                    .then(() => ({ value: { instructions: currentPlayer } }))

                return iterator

            }
    }

}
```

Now any mutation that publishes a new instructions event will return up to date information about the user who subscribed to the instruction subscription.

```javascript
    anyMutation: (_, args, { pubsub }) => {
        pubsub.publish('new-instructions')
    }
```

I was wondering if there is a better way to do this? If there isn't a better way would it be worth adding this functionality to the `asyncIterator`?

**Comment by grantwwu** [comment]
I'm not quite understanding what you're trying to accomplish here.  Surely you could avoid monkey patching by using mapping over the iterator?  The PubSubEngine is really supposed to be the interface to the PubSub system, you shouldn't necessarily put subscription logic into it unless you hvae to.

**Comment by MoonTahoe** [comment]
Users subscribe to asubscription called instructions. Publishing a single event pushes customized, personalized, instructions to eash user. Every payload is different. I do map pver the iterator to push each observer their payload. I’m not pushing the same payload to every observer.  How do I send a unique personalized payload to every connection without monkey patching?

**Comment by grantwwu** [comment]
I see now.  Two ways to accomplish this are:

- `withFilter` on the payloads, filtering out the irrelevant ones
- programmatically determining the trigger you want to use, and passing that into `pubsub.asyncIterator`

**Comment by MoonTahoe** [comment]
Correct me if I am wrong, but if I have 1000 users, `withFilter` allows me to filter out 999 and send the payload to 1 remaining user. So then I have to filter 1000 users 1000 times to get everyone their own playload? Or is there something that I am missing?

I'm not sure what you mean by "programmatically determining the trigger". Where would you use a programmatic trigger in these steps:

1. 1,000 connect and subscribe to a single subscription
2. I publish 'new-instructions'
3. 1,000 users instantly receive their own customized unique payload.

So far, monkey patching is working, and you only iterate through all of subscribers once. I'm just wondering if there is a cleaner, approach for targeting individual subscribers.

**Comment by grantwwu** [comment]
Yes, `withFilter` is inefficient in that aspect.

Okay, I did not understand your use case.  You want to send a payload to each user, once a message arrives on `new-instructions`?

**Comment by grantwwu** [comment]
Have you considered using a for await of loop to accomplish this?

**Comment by hansololai** [comment]
have you looked at the resolve function of subscription?

```
    Subscription = {

        instructions: {
            resolve:(payload, args, context, info){
                // modify the payload, this function is called right after the next() returned data. 
               // If you need to do sql, you can do async/await here too. But it may be slow because you are making a lot of queries.
                return {...payload, currentUser: context.currentUser}
            },
            subscribe(_, args, { pubsub, currentUser }) {
                if (!currentUser) {
                    throw new Error('a user must be logged in to subscribe to instructions')
                }
                const iterator = pubsub.asyncIterator('new-instructions')
                return iterator
            }
    }
```

**Comment by MoonTahoe** [comment]
Cool. Yes that works! In my case It looks like: 

```javascript
Subscription = {

        instructions: {
            resolve:(payload, args, context, info) => context.currentUser,
            subscribe(_, args, { pubsub, currentUser }) {
                if (!currentUser) {
                    throw new Error('a user must be logged in to subscribe to instructions')
                }

                return pubsub.asyncIterator('new-instructions')
            }
    }
```
