### ISSUE TITLE
What's meaning of "It only works if you have a single instance of your server and doesn't scale beyond a couple of connections."?

### ISSUE THREAD

**Issue by mrdulin** [apollographql/graphql-subscriptions#167]
> Note that the default PubSub implementation is intended for demo purposes. It only works if you have a single instance of your server and doesn't scale beyond a couple of connections. For production usage you'll want to use one of the PubSub implementations backed by an external store. (e.g. Redis)

Here is my confuse and case:

1. one front-end app instance, multiple back-end server app instances
2. multiple front-end app instances,  multiple back-end server app instances
3. one front-end app instance, one back-end server app instance

It that mean only case 3 will work fine?

**Comment by jeffreyyoung** [comment]
If you use the pubSub module included in this package only case 3 will work.

`import { PubSub } from 'graphql-subscriptions';
const pubSub = new PubSub(); //only case 3 works
`


If you use a different pubsub implementation like this all cases will work:

`import { RedisPubSub } from 'graphql-redis-subscriptions';
const pubsub = new RedisPubSub(); //cases 1,2,3 work`

**Comment by mrdulin** [comment]
@jeffreyyoung Yes. I am already clear about this issue. thanks for reply
