### ISSUE TITLE
pubsub.Publish not working inside async function

### ISSUE THREAD

**Issue by jomaint** [apollographql/graphql-subscriptions#189]
Im using:
- apollo-subscriptions  1.0.0
- subscriptions-transport-ws  0.9.5

pubsub.publish('event', payload) doesn't emit change to subscribed frontend or graphiql.

However, if i add the below code anywhere in the same file:
    setInterval(() => {
        pubsub.publish('eventName', {
        eventName: { id: '123', name: new Date().toString() },
    });
    }, 2000);

it works. And all subscribed clients will receive the event. 
A short snippet of my code:

resolver:
```
...
    Subscription: {
         eventName: {
             subscribe: async (published, args, ctx, info) => await eventResolver(published, args, ctx, info)
    }
...
```
eventResolver:

```
export const addedPlaceResolver = (published, args, ctx, info) => {
    console.log("called",published, args);
    return pubsub.asyncIterator('eventName');
}
```

exact code elsewhere in my other resolver: 
```

...
pubsub.publish('eventName', { eventName: payload });
...
```

I have event resorted to logging, pubsub.js in graphql-subscriptions/dist and it seems to have received the trigger as well:

pubsub.js
```
...
PubSub.prototype.publish = function (triggerName, payload) {
    console.log('PUBSUB PUBLISHING', triggerName, payload )
    this.ee.emit(triggerName, payload);
    return Promise.resolve();
};
...
```
Appreciate any help if I have missed out something

**Comment by jomaint** [comment]
I got it

**Comment by jomaint** [comment]
I managed to get it to work by doing the follow:
I was using apollo-server 1.4 then i upgraded it to apollo-server 2.2  and it seems to have fixed it. To anyone who encounters this issue in the future, hope this helps you

**Comment by sourabhamancha** [comment]
Hey. I'm facing this very same issue. I'm using apollo-server 2.16.1. I followed your method and it didn't work. Any help would be appreciated.

**Comment by rufaidemir** [comment]
Did you find any solition?

**Comment by sourabhamancha** [comment]
Yess. I was creating a new instance of pubsub, instead of passing the same pubsub object. I fixed it by passing the pubsub object through calls.

**Comment by meirankri** [comment]
thks @sourabhamancha its finaly work for me
