### ISSUE TITLE
Need to see schema for example

### ISSUE THREAD

**Issue by mbabauer** [apollographql/graphql-subscriptions#19]
Maybe I missed it, but it would be nice to see all the relevant pieces of the example, namely what the schema looks like.

**Comment by helfer** [comment]
@mbabauer That's a good idea. Could you make a PR? I think just the subscription part of the schema will be enough.

**Comment by mbabauer** [comment]
@helfer I don't mind making a PR, but where is the example in the README.MD from?

**Comment by helfer** [comment]
@mbabauer it's from GitHunt. You'll find the server part of it in GitHunt-API (apollostack/githunt-api).

**Comment by Darkbladecr** [comment]
Shameless plug, you can see our [example](https://github.com/abhiaiyer91/GraphQL-Chat) and [schema](https://github.com/abhiaiyer91/GraphQL-Chat/blob/master/server/schema.graphql) for a GraphQL Chat backend.

**Comment by dotansimha** [comment]
The README updated with the recent releases, and now there is an example for subscriptions schema, and how to connect it to your subscriptions handler. 
Thanks @mbabauer !
