### ISSUE TITLE
Subscription returns null to subscribed client

### ISSUE THREAD

**Issue by jomaint** [apollographql/graphql-subscriptions#190]
Hi,

Im currently stuck for several days trying to return my payload to my subscribed clients from apollo-server. Somehow the subscribed client did receive the push from server but all values are null. I have verified via 'resolve' on Subscription resolver that my payload is published correctly. But it always reaches my clients with null. I have even resorted to hardcoding my payload and pushing it manually. I have also double checked that my key in payload is 'addedPlace'. Im pretty sure somewhere between subscription resolve function & my client is where the problem is. Hope to hear from anyone who has a clue

**Subscription resolve function log**
![screenshot 2019-01-15 at 11 59 23 am](https://user-images.githubusercontent.com/4236680/51157939-1adbaa80-18bd-11e9-94a2-22a320413fcb.png)

**Client received payload**
![screenshot 2019-01-15 at 11 45 22 am](https://user-images.githubusercontent.com/4236680/51157660-de5b7f00-18bb-11e9-8bc1-9767de8839c7.png)

**Server**
graphql: 14.0.2
apollo-server-express: 2.3.1
subscriptions-transport-ws: 0.9.14
graphql-subscriptions: 1.0.0
graphql-tools: 4.0.3

**Comment by locnguyen** [comment]
@jomaint what was your resolution for this problem? I’m trying to figure out the same for my app.

**Comment by OBannon37** [comment]
Ran into the same symptom. Looks like you should be returning `payload.addedPlace` instead of `payload`, see https://github.com/apollographql/graphql-subscriptions/issues/113
