### ISSUE TITLE
Support async topics

### ISSUE THREAD

**Issue by glentakahashi** [apollographql/graphql-subscriptions#213]
It would be nice to support returning a promise of an AsyncIterator as the ResolverFn. This is also supported in graphql-js https://github.com/graphql/graphql-js/pull/918

This would enable use cases like https://github.com/MichalLytek/type-graphql/issues/470 where we could handle authorization at the topics/resolver level of a subscription, rather than within the filter.

**Comment by jan-wilhelm** [comment]
this is definitely needed. Why is this package no longer maintained?

**Comment by HeyImNoxz** [comment]
any news ?

**Comment by hwillson** [comment]
#220 was merged and will be coming in [release 3.0](https://github.com/apollographql/graphql-subscriptions/pull/250). Thanks!
