### ISSUE TITLE
Is this package still maintained?

### ISSUE THREAD

**Issue by JeffML** [apollographql/graphql-subscriptions#228]
Last published update was 11 months ago.  Currently there are 14 pull requests.

**Comment by AadamZ5** [comment]
Seems like there was a push to master branch, commit [2baf18a44c61e3d51d1a55bd1a0ea0b6769c9e91](https://github.com/apollographql/graphql-subscriptions/commit/2baf18a44c61e3d51d1a55bd1a0ea0b6769c9e91) from 7/16/20.

**Comment by JeffML** [comment]
Ok, look like some dependency updates but Al's a minor code change. Closing.
