### ISSUE TITLE
Push to npm

### ISSUE THREAD

**Issue by jacklp** [apollographql/graphql-subscriptions#231]
please push the peerDependencies changes you made to npm

**Comment by zerocewl** [comment]
What is blocking this issue?

**Comment by b-jsshapiro** [comment]
This is making a mess of builds in lots and lots of places. In some opinions, failed dependencies are a breaking change. Can we please get this pushed?

**Comment by glen-84** [comment]
Version 1.2.0 has been released to npm (but is not yet tagged in GitHub). This issue can probably be closed.

/cc @glasser

**Comment by glasser** [comment]
Oops, sorry about the lack of git push (I'm spoiled by the CI-based publishing we have on other repos). Agreed, this is fixed!
