### ISSUE TITLE
Release the package

### ISSUE THREAD

**Issue by oliversalzburg** [apollographql/graphql-subscriptions#238]
Please publish a package with the latest changes. The warnings about unmet peer dependencies start to get really annoying.

**Comment by valdestron** [comment]
Please do! We have to workaround for unment peer dependencies for graphql ^15.0.0 as this package requires at most ^14.0.0

**Comment by glen-84** [comment]
Version 1.2.0 has been released to npm (but is not yet tagged in GitHub). This issue can probably be closed.

/cc @glasser

**Comment by oliversalzburg** [comment]
Thanks!

**Comment by glasser** [comment]
Oops, sorry about the lack of git push (I'm spoiled by the CI-based publishing we have on other repos). Agreed, this is fixed!
