### ISSUE TITLE
Peer Dependency Mismatch

### ISSUE THREAD

**Issue by DakotaLarson** [apollographql/graphql-subscriptions#242]
Hi, 

When installing graphql-subscriptions as a dependency of type-graphql or apollo-server-express, I get an error stating it requires a peer dependency of `graphql@^0.10.5 || ^0.11.3 || ^0.12.0 || ^0.13.0 || ^14.0.0`.

 The code in this repo uses `^0.10.5 || ^0.11.3 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0`, allowing v15.x which I have installed.

 I installed the package fresh from npm in a test folder and got the same peer dependency. 

Essentially, can package.json be updated to support v15.x and be in line with the code in this repo?

Thanks!

**Comment by ezforw** [comment]
having a similar issue there, need support for graphql v15

```
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: graphql@15.4.0
npm WARN node_modules/graphql
npm WARN   graphql@"^15.4.0" from the root project
npm WARN   43 more (@apollo/client, @graphql-cli/codegen, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer graphql@"^0.10.5 || ^0.11.3 || ^0.12.0 || ^0.13.0 || ^14.0.0" from graphql-subscriptions@1.1.0
npm WARN node_modules/graphql-subscriptions
npm WARN   graphql-subscriptions@"^1.1.0" from openapi-to-graphql@2.2.5
npm WARN   node_modules/openapi-to-graphql
```

**Comment by theodorDiaconu** [comment]
The code is there, but I think it's not published to 1.1.0.

**Comment by theodorDiaconu** [comment]
@hwillson please help us! We hate seeing peer dependencies error mismatch and we're all using graphql@15. 

These commands should solve it (for your convenience), as the package.json is already updated:
```bash
npm version patch
git push ; git push --tags;
npm publish
```

**Comment by glen-84** [comment]
Version 1.2.0 has been released to npm (but is not yet tagged in GitHub). This issue can probably be closed.

/cc @glasser

**Comment by glasser** [comment]
Oops, sorry about the lack of git push (I'm spoiled by the CI-based publishing we have on other repos). Agreed, this is fixed!
