### ISSUE TITLE
Add apollo and relay example

### ISSUE THREAD

**Issue by sibelius** [apollographql/graphql-subscriptions#28]
it would be really nice to have an apollo and a relay example of usage of this package

**Comment by stubailo** [comment]
Good call - has anyone implemented Relay support for this transport yet? If not, that would be the first step.

**Comment by jamesone** [comment]
Has anyone found a example?

**Comment by dotansimha** [comment]
At the moment, we have a great example for subscriptions with Apollo: http://dev.apollodata.com/react/subscriptions.html

**Comment by jamesone** [comment]
Nice @dotansimha Hopefully we get a relay modern example soon :) There isn't one anywhere yet. There are a couple of apollo examples already!

**Comment by evenchange4** [comment]
Here is my practice of fullstack todoMVC with apollo:
https://github.com/evenchange4/todomvc-subscriptions
Any feedbacks are welcome~

**Comment by hwillson** [comment]
Thanks for the suggestion; we're doing a bit of house cleaning on this repo so we'll close this off, but if anyone is ever interested in doing this let us know. Hosting the example outside of the repo is probably best, but we'll link to it from the README. Thanks!
