### ISSUE TITLE
pass variables to pub sub?

### ISSUE THREAD

**Issue by gilesbradshaw** [apollographql/graphql-subscriptions#31]
I've hacked your code so it does

````
// 3. subscribe and keep the subscription id
            const subsPromise = this.pubsub.subscribe(triggerName, onMessage, channelOptions, options.variables);
````

rather than..

````
// 3. subscribe and keep the subscription id
            const subsPromise = this.pubsub.subscribe(triggerName, onMessage, channelOptions);
````

this means I can implement pubsub so it subscribes to an external event source (dont worry about details):

````
const valueSubscriptions = {};

class MyPubSub extends PubSub {

  subscribe(trigger, onMessage, channelOptions, variables){
    const ret = super.subscribe(trigger, onMessage);
    if (trigger === 'value') {
      ret.then(f => valueSubscriptions[f] = opcObserver(variables.id).subscribe(v => pubsub.publish('value', v)));
    }
    return ret;
  }
  unsubscribe(subid) {
    if (valueSubscriptions[subid]) {
      valueSubscriptions[subid].unsubscribe();
      delete valueSubscriptions[subid];
    }
    return super.unsubscribe(subid);
  }

}
````

would this make sense for you to incorporate?

**Comment by dotansimha** [comment]
@gilesbradshaw do you think this issue and PR are relevant after the recent refactor of this package? 
The `PubSub` now is just an event source, and each event is treated as a stream, and you can connect it directly to your GraphQL schema and add custom handler there.

**Comment by gilesbradshaw** [comment]
Hi probably not - but not looking at it right now (up to my eyeballs in other stuff atm)  feel free to close if you feel it's no longer relevant :)

**Comment by dotansimha** [comment]
👍 @gilesbradshaw
