### ISSUE TITLE
Consider handling the errors thrown in setupFunction and make it promisable.

### ISSUE THREAD

**Issue by ezsper** [apollographql/graphql-subscriptions#34]
On file `pubsub.ts` on line 162, the setupFunction should be handling the errors thrown in the function. That is important because we can decline and authorize subscriptions directly in the setupFunction itself. And by having this in mind you should make the setupFunction promisable for security async operations,  like the `onSubscribe` method.

![should handle as promise](https://cloud.githubusercontent.com/assets/798804/21951938/d148a316-d9f6-11e6-8e79-e1662330c4e8.PNG)

In my case this is important because I have different authorization methods, and one can be invalid depending on the subscription.

Here's an example of how I would be able to use it.

![example usage](https://cloud.githubusercontent.com/assets/798804/21952094/79bcce2a-d9fa-11e6-945f-fc594f44d166.PNG)

**Comment by stubailo** [comment]
Would you mind opening two specific issues? It looks like there are two different feature requests rolled into one here.

**Comment by ezsper** [comment]
You're right. Done.

**Comment by ezsper** [comment]
Please, consider this issue.

**Comment by NeoPhi** [comment]
@ ezsper This looks like a helpful improvement. A PR would be very welcome!

**Comment by dotansimha** [comment]
@ezsper We recently released a new version of the package, and now `SubscriptionsManager` and `setupFunctions` are deprecated. Instead, you can implement your own `AsyncIterator` as the event stream.
You can implement the `filter` using `withFilter` in your `subscribe` resolver that wraps existing `AsyncIterator` with a custom filter function (you can also return `Promise` there), and you can add the payload transformation using `resolve` (which also accepts `Promise` as return value).

```js
{
    issuedUserNotification: {
        resolve: (payload) => { return payload; } // transformation,
        subscribe: withFilter(() => pubsub.asyncIterator('myEvent'), () => true) // filter
   },
}
```
