### ISSUE TITLE
Besides filter, add a property to format rootValue

### ISSUE THREAD

**Issue by ezsper** [apollographql/graphql-subscriptions#35]
You should have another property besides filter for trigger map which could clean the rootValue before executing on graphql and submitting to the client, a suggestion would be a promisable (!) `format` or even a `resolve` property.

On file `pubsub.ts` on line 197,

![before execute](https://cloud.githubusercontent.com/assets/798804/21952015/74aa0fbc-d9f8-11e6-98fd-1a80aa5781ce.PNG)

In my case this is important because I need to remove private values on an object type when the client authorized is not eligible to see it.

The following is an example of how I would be able to use it.

![example usage](https://cloud.githubusercontent.com/assets/798804/21952094/79bcce2a-d9fa-11e6-945f-fc594f44d166.PNG)

**Comment by ezsper** [comment]
Please, consider this issue.

**Comment by NeoPhi** [comment]
@ ezsper This looks like a helpful improvement. A PR would be very welcome!

**Comment by micha149** [comment]
Oh, this would be helpful for me, too. I need to pass the channel name into the result. There seem currently no way.

Your example looks like a pure mapping function which will be called for each message, right? So, I would suggest to call it `map`, which fits nice to `filter`.

Did someone already started an implementation?

**Comment by dotansimha** [comment]
It's available in the recent release, using the new `graphql-js` subscriptions API, see my comment here: https://github.com/apollographql/graphql-subscriptions/issues/34#issuecomment-305115013
