### ISSUE TITLE
Can not resolve field that is not part of the published object

### ISSUE THREAD

**Issue by n1ru4l** [apollographql/graphql-subscriptions#52]
What I am using:

**react-native**: 0.42.3
**react-apollo**: 1.0.0-rc.3
**apollo-client**: 1.0.0-rc.6
**subscriptions-transport-ws**: 0.5.5-alpha.0
**graphql-subscriptions**: ^0.3.1

I have the following schema:
```graphql
type Episode {
  id: Int!
  number: String!
  title: String!
  cover: String!
}

type CastQueueItem {
  itemId: Int!
  episode: Episode!
}

type CastStatus {
  queueItems: [CastQueueItem]!
}

type Subscription {
  castStatus: CastStatus!
}

schema {
  query: Query # not included
  mutation: Mutation # not included
  subscription: Subscription
}
```

This is my Subscription to which I subscribe in my react-native application:
```graphql
subscription castStatus {
  castStatus { 
    queueItems {
      itemId
      episode {
        id
        title
        cover
      }
    }
  }
}
```
Somewhere in my javascript I publish the CastStatus:
```javascript
const castStatus = {
  queueItems: [
    { itemId: 1, episode: { id: 1, title: '1', },
    { itemId: 2, episode: { id: 2, title: '2', },
  ],
}
pubsub.publish(`castStatus`,  { castStatus })
```

The cover field has a resolver that exists on the schema I passed to the SubscriptionManager constructor.

I am expecting the cover field to be resolved trough my schema - but it seems not to work. I am getting no updates from the server as long as I the cover field is listed in my subscription. Also, I am not getting any error message :(

I wanted to ask if this behavior is on purpose and if so why SubscriptionManager does not resolve field via the schema.

**Comment by NeoPhi** [comment]
How are you constructing your schema? This seems related to #51.

**Comment by n1ru4l** [comment]
I am constructing my schema with https://github.com/apollographql/graphql-tools

I also just realized that there is no context available - so it can not work. According to the documentation I will have to return a context in the `onConnect` lifecycle event. I am going to try this later.

**Comment by n1ru4l** [comment]
Ok, by adding a Subscription resolver and by returning a context in the onConnect lifecyle event this works.

**Comment by initialspark** [comment]
Hey 

i have the same issue and have added in the context to the lifecycle event but still in the apollo client it says the context doesn't exist for the type when trying to resolve it.

'context.collection is not a function'

Any advise?

Thanks,

Sam

**Comment by n1ru4l** [comment]
@initialspark Could you please provide some code?

**Comment by initialspark** [comment]
I managed to solve this in the end thanks
