### ISSUE TITLE
The terminology is confusing (at least for me)

### ISSUE THREAD

**Issue by deiucanta** [apollographql/graphql-subscriptions#55]
I've struggled for a couple hours last night to get this but I couldn't.

---

Snippet 1

```js
subscription($repoName: String!) {
  commentAdded(repoName: $repoName) { # <-- `commentAdded` is the subscription name
    id
    content
  }
}
```

Snippet 2

```js
const subscriptionManager = new SubscriptionManager({
  schema,
  pubsub,
  setupFunctions: {
    commentAdded: (options, args) => ({
      commentAdded: {
        filter: comment => comment.repository_name === args.repoFullName,
      },
    }),
  },
});
```

Snippet 3

```js
pubsub.publish('commentAdded', payload);
```

---

I have a couple questions

1. In the 1st snippet `commentAdded` is the subscription name and in the 3rd snippet `commentAdded` is the event name. Are those the same thing?
2. Why `commentAdded` appears twice in `setupFunctions` of the 2nd snippet? Wouldn't this be enough?

    ```js
    const subscriptionManager = new SubscriptionManager({
      schema,
      pubsub,
      setupFunctions: {
        commentAdded: (options, args) =>
          payload => payload.repository_name === args.repoFullName,
      },
    });
    ```

3. The example from the main readme of this repo confused me even more. The subscription name is `commentAdded` but the event name is `newCommentsChannel`. How is the event name constructed? Do you simply append `Channel` to the end of the operation name (`newComments` in this case)? Isn't the operation name optional?

    ```js
    subscription newComments($repoName: String!){
      commentAdded(repoName: $repoName) { # <-- this is the subscription name
        id
        content
        createdBy {
          username
        }
      }
    }
    ```

**Comment by scf4** [comment]
@deiucanta I agree, the apollo docs for subscriptions are a little confusing at the moment. 

In short, `setupFunctions` maps subscriptions to pubsub channels. 

When you call `pubsub.publish('commentAdded', { ... })`, you're publishing to the `commentAdded` channel. The mapping in `setupFunctions` means this channel will trigger the `commentAdded` subscription (if the filter function returns true). I *think* (not sure) that you can leave out the `setupFunctions` and it will map channel names to subscriptions of the same name by default. 

For clarification, the first `commentAdded` is the subscription name, the second is the channel name.

Take a look at the example and description here: https://github.com/davidyaha/graphql-redis-subscriptions. That's for `graphql-redis-subscriptions` but the idea is the same.

**Comment by scf4** [comment]
I've fixed up the readme with this pr https://github.com/apollographql/graphql-subscriptions/pull/56
