### ISSUE TITLE
Eventemitter3

### ISSUE THREAD

**Issue by gaston23** [apollographql/graphql-subscriptions#58]
Allow to use other EventEmitters? 

Like https://github.com/primus/eventemitter3 

Thanks

**Comment by NeoPhi** [comment]
It is possible to use any PubSub mechanism that adheres to the `PubSubEngine` interface. The included PubSub implementation is a minimal example. See https://github.com/davidyaha/graphql-redis-subscriptions for an alternative PubSub implementation.
