### ISSUE TITLE
How to publish to concrete subscribers?

### ISSUE THREAD

**Issue by akaNightmare** [apollographql/graphql-subscriptions#61]
Hi, for example - chat with rooms and private messages...
Also how to get all subscribers in the room?

**Comment by NeoPhi** [comment]
The filter function would be used to ensure that a published message is only delivered to the intended recipient. There is no support to push a message directly to a client.

Depending on what network transport you are using, it should have facilities to track the subscribers. See [onSubscribe and onUnsubscribe ](https://github.com/apollographql/subscriptions-transport-ws#constructoroptions-socketoptions) of subscriptions-transport-ws.
