### ISSUE TITLE
Warning: Resolve function missing

### ISSUE THREAD

**Issue by cncolder** [apollographql/graphql-subscriptions#66]
In [Readme - Payload Manipulation](https://github.com/apollographql/graphql-subscriptions#payload-manipulation) writing _You can __also__ manipulate the published payload_.

But if I not set resolve method. There is a warning show me `Resolve function missing for "Subscription.commentAdded". To disable this warning check https://github.com/apollostack/graphql-tools/issues/131`

To resolve this I must set a passthrough function.

```js
    commentAdded: {
      resolve: root => root,
      subscribe: () => pubsub.asyncIterator('commentAdded')
    }
```

Is this a bug or change readme to `You must manipulate the published payload, by adding resovle methods to your subscription`

**Comment by dotansimha** [comment]
I guess that now that we are using the new subscriptions, `graphql-tools` should allow a resolver to use `subscribe` only, without adding `resolve` (only in case of subscriptions resolvers).

@Urigo @helfer @stubailo @DxCx  what do you think?

**Comment by DxCx** [comment]
hmm, @dotansimha IMO we need to not force resolvers for subscriptions
and add one more mapping of subscriptions so we can introduce addSubscriptionsToSchema as well..

**Comment by dotansimha** [comment]
@DxCx can you explain?
Why not omit this warning when dealing with subscriptions? I am not sure that we need `addSubscriptionsToSchema`

**Comment by drFabio** [comment]
I got this warning and fixed it but my subscribe never get's called. Is there anything more  that needs to be done with the resolver?

**Comment by jamiter** [comment]
To make the example metioned by @cncolder work, it has to be in this format (in the current version):

```
commentAdded: {
  resolve: root => root.commentAdded,
  subscribe: () => pubsub.asyncIterator('commentAdded')
}
```

I updated the documentation in this PR: https://github.com/apollographql/graphql-subscriptions/pull/134

**Comment by hwillson** [comment]
https://github.com/apollographql/graphql-subscriptions/pull/134 was merged so I'll close this off. Thanks!
