### ISSUE TITLE
Using an external PubSub engine

### ISSUE THREAD

**Issue by emmanuelvacher** [apollographql/graphql-subscriptions#70]
Hello,

I would like to know if it is possible to use `graphql-mqtt-subscriptions` along with this package. More precisely, I'd like someone to explain how to wrap a pubsub with an `AsyncIterator` since the apollo client needs one for the subscription to be effective.

My final goal is to use a MQTT broker to handle subscriptions instead of the in-memory pubsub engine provided by your package.

Thank you for your help.

**Comment by dotansimha** [comment]
@emmanuelvacher 

Basically, you can implement any `PubSub`, the only thing that is important is to return `AsyncIterator` as your subscription stream.

You can implement your own logic and transform your MQTT subscription into an `AsyncIterator` and use it as your subscriptions stream.

`AsyncIterator` API should implement the `AsyncIterator` symbol, `next`, `return` and `throw` methods.
This is an example for a simple `AsyncIterator` that maps Redis subscriptions into an `AsyncIterator` (haven't tested it, but it should work 😆 ):

```ts
import { $$asyncIterator } from 'iterall';

const redisClient = createClient({ host, port, password });

const redisEventToAsyncIterator = (redisClient: RedisClient, eventName: string) => {
  let promiseResolve;

  redisClient.on('message', (channel: string, message: string) => {
    const parsedMessage = JSON.parse(message);

    if (promiseResolve && eventName === channel) {
      promiseResolve(parsedMessage);
    }
  });

  return {
    next() {
      return new Promise(resolve => {
        promiseResolve = resolve;
      }).then(value => ({
        done: false,
        value,
      }));
    },
    return() {
      return Promise.resolve({ done: true, value: undefined });
    },
    throw(e: Error) {
      return Promise.reject(e);
    },
    [$$asyncIterator]() {
      return this;
    },
  };
};
```

Then, you can use it as your subscriptions stream, in your resolver:

```ts
const REDIS_EVENT_NAME = 'something_changed';

const resolvers = {
   Subscription: {
        somethingChanged: {
             subscribe: () => redisEventToAsyncIterator(client, REDIS_EVENT_NAME),
        }
   }
}
```

And then, each time your Redis instance publishes a message - it will map this message to your GraphQL subscription. 

You can see other implementations for `AsyncIterator` here:

* [`AsyncIterator` from `AsyncIterator` with filter logic](https://github.com/apollographql/graphql-subscriptions/blob/master/src/with-filter.ts)
* [`AsyncIterator` from `EventEmitter`](https://github.com/apollographql/graphql-subscriptions/blob/master/src/event-emitter-to-async-iterator.ts)
* [`AsyncIterator` from `Promise`](https://github.com/apollographql/subscriptions-transport-ws/blob/master/src/utils/promise-to-iterable.ts)
* [Empty `AsyncIterator`](https://github.com/apollographql/subscriptions-transport-ws/blob/master/src/utils/empty-iterable.ts)
* [`Error` to `AsyncIterator`](https://github.com/apollographql/subscriptions-transport-ws/blob/master/src/utils/rejection-iterable.ts)

The `graphql-mqtt-subscriptions` and `graphql-redis-subscriptions` uses the old API of subscriptions, and it needs an update (@davidyaha), but you can simply implement it now with a custom `AsyncIterator`.

**Comment by emmanuelvacher** [comment]
@dotansimha Thank you very much, I'm going to try that.

**Comment by dotansimha** [comment]
@emmanuelvacher did you managed to implement your own `AsyncIterator`? can we close this issue?

**Comment by emmanuelvacher** [comment]
@dotansimha yes I managed to implement my own `AsyncIterator` thanks to your advice :+1: you can close this issue.

**Comment by patricknazar** [comment]
I've tried this but I cannot seem to receive any messages. Redis client connects ok, sends its own messages ok, but doesn't receive them. I'm guess because there's a redisClient.subscribe() missing somewhere? If so, then probably an unsubscribe is important too. Please help
