### ISSUE TITLE
Memory leak: event handlers are not removed when a subscription ends

### ISSUE THREAD

**Issue by kouak** [apollographql/graphql-subscriptions#73]
Versions used :
* graphql-subscriptions 0.4.2
* subscription-transport-ws 0.7.1

When a subscription is created, event handlers are created and registered through the underlying EventEmitter class.

However, these event handlers are never removed leading to a memory leak.

Now, I don't know whether the bug lies in this repo or in `subscriptions-transport-ws` as I'm not familiar enough with this codebase yet.

However, I managed to reproduce the issue in the Githunt-API example implementation.

### Steps to reproduce
* Clone my fork of GitHunt-API: https://github.com/kouak/GitHunt-API

My only change is to `console.log` registered event handlers in the underlying EventEmitter object every 5 seconds.

* Setup the project as described in the README
* Start the server
* Start a subscription in GraphiQL
* Watch the event handler registered in console output
* Close GraphiQL tab, reopen, and register a new subscription
* Watch both event handlers in console output
* Rince & repeat until OOM :)

**Comment by NeoPhi** [comment]
Possibly related to https://github.com/apollographql/subscriptions-transport-ws/issues/154

**Comment by Urigo** [comment]
released in `0.4.3`
