### ISSUE TITLE
pattern for getting initial subscription payload

### ISSUE THREAD

**Issue by dnalborczyk** [apollographql/graphql-subscriptions#75]
I was wondering what a good pattern would be for receiving an _initial_ subscription payload?

let me try to explain with the help of some contrived examples:

if we run the code from the docs ...

```
// hooking up subscription resolvers etc., simplified
const resolvers = {
  Subscription: {
    getReport: {
      subscribe: () => ....
// ...

// then run ...
pubsub.publish( 'somethingChanged', { getReport: { id: "1" }});
```

then the subscription query would not receive any payload:
```
subscription {
   getReport {
      id
   }
}
```

... unless we are triggering publish, e.g. through a Mutation.
```
function publish() {
   pubsub.publish( 'somethingChanged', { getReport: { id: "1" }});
}

const resolvers = {
  Mutation: {
    triggerReport: () => publish()
```

e.g. we could also make it work this way - just to have a (bad) example:

```
setInterval( () =>
   pubsub.publish( 'somethingChanged', { getReport: { id: "1" }})
), 1000 );
```

My understanding is that one would usually use a _Mutation_ in order to _trigger_ publish.
I was wondering how could one receive the initial payload without a trigger?

Unless subscriptions are only meant to be published through some sort of trigger?

Or would one get the initial payload through an ordinary graphql _query_?

```
query {
   getReport {
      id
   }
}
```

Thanks in advance for any advice!

**Comment by dotansimha** [comment]
@dnalborczyk 
The actual pattern for this use case is to use `Query` to fetch the initial state, and then use `subscription` to get real-time updates about data changes (usually the changes are driven from a mutation). 

If your use case insist on publishing data when client connects, you can use `onOperation` callback of the `subscriptions-transport-ws` and publish data there, but note that your PubSub is shared between all clients, so you probably need to create your own implementation for `AsyncIterator` that wraps an existing Iterator (the shared one from your PubSub) and adds a custom payload publication for a specific user.

**Comment by dnalborczyk** [comment]
just noticed I didn't leave a message in June :/

thank you  so much @dotansimha !!!

**Comment by acro5piano** [comment]
I was in the same situation and this blog post was great.

https://ralexanderson.com/blog/subscription-only-graphql-data
