### ISSUE TITLE
Typescript no longer compile : Generic type 'AsyncIterator<T, E>' requires 2 type argument(s)

### ISSUE THREAD

**Issue by mgrenier** [apollographql/graphql-subscriptions#77]
`graphql-subscriptions` no longer compile with Typescript. AsyncIterator from @types/async requires 2 type arguments.

I'm using `graphql-subscriptions@0.4.1`.

Had to manualy add the second type in `*.d.ts` files from `graphql-subscriptions` to make it work.

**Comment by marklawlor** [comment]
I believe this issue is more related to the @types/async package.

https://github.com/DefinitelyTyped/DefinitelyTyped/issues/16980

**Comment by dotansimha** [comment]
@mgrenier please provide the following:
- TypeScript compiler version
- Bundler type (webpack? angular cli?)
- tsconfig.json lib section

Thanks

**Comment by mgrenier** [comment]
@dotansimha 
```
typescript@2.3.4
webpack@2.6.0
tsconfig
{
  "compilerOptions": {
    "outDir": "build/dist",
    "module": "commonjs",
    "target": "esnext",
    "lib": ["es6", "dom"],
    "sourceMap": true,
    "allowJs": true,
    "jsx": "react",
    "moduleResolution": "node",
    "rootDir": "src",
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": false,
    "strictNullChecks": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": true
  },
  "exclude": [
    "node_modules",
    "build",
    "scripts",
    "acceptance-tests",
    "webpack",
    "jest",
    "src/setupTests.ts"
  ],
  "types": [
    "typePatches"
  ]
}
```

**Comment by dotansimha** [comment]
@mgrenier Please try to add `esnext` to your `lib` section in `tsconfig.json`, and also remove any manual typings for `AsyncIterator`.

**Comment by bruce** [comment]
Is there another workaround we can try? (If this package is using the new typescript AsyncIterator approach, I'm not sure it gets resolved here vs, eg, apollo-client)

**Comment by veeramarni** [comment]
to be more specific, I have used the following. 

```
    "lib": [
      "es2017",
      "dom",
      "esnext.asynciterable"
    ],
```

**Comment by dotansimha** [comment]
@mgrenier we can close this issue? did you managed to run it?

**Comment by bruce** [comment]
Neither adding "esnext.asynciterable" (or just plain "esnext") solved the compilation problem for me.

Error:
```
node_modules/@types/async/index.d.ts(15,11): error TS2428: All declarations of 'AsyncIterator' must have identical type parameters.
node_modules/typescript/lib/lib.esnext.asynciterable.d.ts(32,11): error TS2428: All declarations of 'AsyncIterator' must have identical type parameters.
node_modules/typescript/lib/lib.esnext.asynciterable.d.ts(39,31): error TS2314: Generic type 'AsyncIterator<T, E>' requires 2 type argument(s).
node_modules/typescript/lib/lib.esnext.asynciterable.d.ts(42,44): error TS2314: Generic type 'AsyncIterator<T, E>' requires 2 type argument(s).
```

tsconfig:
```
{
  "compilerOptions": {
    "module": "commonjs",
    "moduleResolution": "node",
    "rootDir": "./src",
    "target": "es5",
    "sourceMap": true,
    "strictNullChecks": true,
    "outDir": "./pkg/lib",
    "lib": ["dom", "esnext"]
  },
  "exclude": [
    "node_modules"
  ]
}
```

```
$ tsc --version
Version 2.4.1
```

Code at https://github.com/absinthe-graphql/absinthe-phoenix-apollo-js

**Comment by bruce** [comment]
Perhaps this should _really_ be addressed in https://github.com/DefinitelyTyped/DefinitelyTyped/issues/16980. The `esnext` fix didn't work for me.

**Comment by curtiswilkinson** [comment]
Hey @bruce, if you checkout https://github.com/apollographql/subscriptions-transport-ws/issues/175#, you'll see I mention a quick workaround 

It's a combination of using `esnext` as a TS lib and a package.json postInstall script to remove the conflicting @types/async definition upon package installs:
`"postinstall": "rm - rf node_modules/@types/async"`

It's a hack but I thought I'd mention it to you so you're not blocked entirely.

**Comment by emmanuelbuah** [comment]
Will this be address soon without quick workaround?

**Comment by buggy** [comment]
In addition to using `esnext` I had to `npm install @types/async@2.0.31 --save-dev` to get it to use a compatible version as apollo-client (required by the tool I'm using) was using an incompatible version.

**Comment by stevewpatterson** [comment]
@buggy That fixed my conflict, thanks alot!

**Comment by sibelius** [comment]
lib: [
    "esnext"
]

solves the problem
