### ISSUE TITLE
Can keystone.js be used along with the graphql subscriptions

### ISSUE THREAD

**Issue by nimish-gupta** [apollographql/graphql-subscriptions#85]

**Comment by dotansimha** [comment]
@nimish-gupta 
I am not familiar with KeystoneJS, but you can integrate GraphQL and GraphQL Subscriptions with any NodeJS and JavaScript client. 
Can you explain your specific use case?

**Comment by grantwwu** [comment]
Closing just to clean this up because there hasn't been any activity in a while.  Feel free to respond with more details
