### ISSUE TITLE
Subscription must return Async Iterable when using withFilter

### ISSUE THREAD

**Issue by gergely-ujvari** [apollographql/graphql-subscriptions#89]
I was trying to use filtering explained in the [official documentation](http://dev.apollodata.com/tools/graphql-subscriptions/setup.html#filter-subscriptions)  but it fails with the "Subscription must return Async Iterable" error.

Here is my example for my `Subscription resolver`:

This doesn't work:
```
Subscription: {
    errorChanged: {
        subscribe: () => withFilter(
            () => pubsub.asyncIterator("errorChanged"),
            (payload, variables) => {
                return true;
            },
        ),
    },
}
```

This works:
```
Subscription: {
    errorChanged: {
       subscribe: () => pubsub.asyncIterator("errorChanged")
    },
}
```

Am I doing something wrong?

Using version: 0.4.4

**Comment by gergely-ujvari** [comment]
Sorry, I was doing something wrong.

**Comment by igorlimansky** [comment]
hey, @gergely-ujvari , can you, please, share details about what exactly you was doing wrong? :)

**Comment by gergely-ujvari** [comment]
If I can remember well then the solution is not to wrap the `withFilter`  with an another function,
so like this:
```javascript
Subscription: {
    errorChanged: {
        subscribe: withFilter(
            () => pubsub.asyncIterator("errorChanged"),
            (payload, variables) => {
                return true;
            },
        ),
    },
}
```
