### ISSUE TITLE
Publish events

### ISSUE THREAD

**Issue by anhldbk** [apollographql/graphql-subscriptions#91]
Hi guys,

In file `README`, currently we have the demo code to publish events:

```js
pubsub.publish(SOMETHING_CHANGED_TOPIC, { somethingChanged: { id: "123" }});
```

I tried to use the template above but in clients, I've got nothing. All fields are set to `null`. But if I modify it a little bit like this:

```js
pubsub.publish(SOMETHING_CHANGED_TOPIC, {  id: "123" });
```

It works as expected. So is there any thing wrong with the documentation?

**Comment by anhldbk** [comment]
Well, in [src/pubsub.ts](https://github.com/apollographql/graphql-subscriptions/blob/master/src/pubsub.ts#L16):

```js
  public publish(triggerName: string, payload: any): boolean {
    this.ee.emit(triggerName, payload);

    return true;
  }
```

Definitely I think there's an error in the documentation regarding this issue.

**Comment by rnenjoy** [comment]
If i dont have { somethignChanged:   .... i get null. So i have the opposite?

**Comment by anhldbk** [comment]
@rnenjoy I don't know. What're your related packages? Mine are:

```
    "apollo-client": "^1.9.0-1",
    "graphql-tag": "^2.4.2",
    "react-apollo": "^1.4.7",
    "subscriptions-transport-ws": "^0.8.1"

```

**Comment by grantwwu** [comment]
It's been a while since this bug was reported.  If you're still encountering this, please reply... and a working reproducer would also be nice :)
