### ISSUE TITLE
[Question] how to use with graphql-js?

### ISSUE THREAD

**Issue by eladams** [apollographql/graphql-subscriptions#94]
It seems that `SubscriptionManager[@deprecated]` was meant for that so I'm a bit lost 🗺

**Comment by NeoPhi** [comment]
Newer versions of `graphql-js` support subscriptions directly. For a step by step walkthrough of using this package I recommend looking through: http://dev.apollodata.com/tools/graphql-subscriptions/index.html

**Comment by sibelius** [comment]
is there any example of `graphql-js` with this package?

**Comment by NeoPhi** [comment]
In the documentation mentioned above at http://dev.apollodata.com/tools/graphql-subscriptions/setup.html#subscription-server you'll see it uses `import { execute, subscribe } from 'graphql';`

**Comment by sibelius** [comment]
I think the problem is with this doc

```jsx
Subscription: {
        commentAdded: {
          subscribe: withFilter(() => pubsub.asyncIterator('commentAdded'), (payload, variables) => {
             return payload.commentAdded.repository_name === variables.repoFullName;
          }),
        }
    },
```

it is not in graphql-js notation, I think this cause some problems for newcomers

**Comment by eladams** [comment]
Exactly @sibelius, do you have any suggestions?

**Comment by igorlesnenko** [comment]
You just need to put `subscribe` function on the same level where `resolve` is located. Example:

```js
 let subscription = {
      type: new GraphQLObjectType({
        name: subscriptionName,
        fields: () => ({
          mutation: { type: GraphQLString },
          node: {
            type: modelTypes[model.getName()]
          }
        })
      }),
      subscribe: () => {
        return PubSubService.asyncIterator(subscriptionName);
      }
};
```

**Comment by grantwwu** [comment]
This issue _seems_ to be resolved, closing, let me know if it's not
